### PR TITLE
Add autocomplete question type. 

### PR DESCRIPTION
**Pull request by joaquingx**
This PR implements autocomplete feature:

```
def ask_pystyle(**kwargs):
    # create the question object
    question = questionary.autocomplete(
        "Choose ant specie",
        choices=[
            'Camponotus pennsylvanicus',
            'Linepithema humile',
            'Eciton burchellii',
            "Atta colombica",
            'Polyergus lucidus',
            'Polyergus rufescens',
        ],
        **kwargs)

    # prompt the user for an answer
    return question.ask()
```

Retaled to #20

### CODE REVIEW

**Comment by joaquingx** [comment]
Hey @tmbo, can you give me a review please :smile:

**Comment by joaquingx** [comment]
How its going @tmbo ?

**Comment by yardensachs** [comment]
Should this be a feature in select instead of a different type?

**Comment by tmbo** [comment]
yes that is actually a good idea. I guess it comes down to the use case: 

Is this meant to just suggest entries, but allow arbitrary user input ? -> if so should merge with text

OR

Is this more a better UI for a list with lots of items where you are supposed to select one (like a select, but with lots of items)? --> if so should be separate component

**Comment by joaquingx** [comment]
@tmbo Actually, it allows arbitrary user input. Also, with a proper validation(https://github.com/tmbo/questionary/pull/21/files#diff-9839c6f9a625f87aef5dc23f53bb6e14R76) it will only allows input that are in `choices`. At first sight i think is possible to merge autocomplete with text but it will increase text complexity.

**Pull request merged**
