### PR TITLE
Starting points in lists and optional shortcut keys

### PR DESCRIPTION
**Pull request by philastrophist**
Summary of prosed changes:
In `select` and `checkbox`:

- Option to stop displaying the current answer verbosely
- Option to start the arrow at different points other than the first choice

In `select`:

- Option to use arrow keys and shortcuts to move the arrow at the same time
- Option to not assign shortcuts to specific choices (not disabling them, but making them only reachable by arrow keys). 
- <s>Removal of navigation by i and j keys to avoid confusion.</s> (put back)

Passing tests are included for these additions.

### CODE REVIEW

**Comment by elrony** [comment]
Hello,
Was wondering when this is going to be merged as I would really like for both keyboard navigation and shortcuts to work at the same time.

Thanks,
r

**Comment by Zethson** [comment]
@tmbo I quite like this feature and wanted to ask whether you could merge this PR?

**Comment by kiancross** [comment]
@philastrophist Any chance you could have a look at the conflicts so we can get it merged in?

**Comment by philastrophist** [comment]
I will fix these errors in a bit. Just busy right now

**Comment by kiancross** [comment]
@philastrophist Ok no problem. Please make sure you run `black questionary` over your code so it passes the code style tests.

**Comment by kiancross** [comment]
I'm working on merging this at the moment.

- I've removed _"Option to start the arrow at different points other than the first choice"_, as this has already been implemented.

(in progress)

**Review by kiancross — APPROVED** [review]
Since this PR, the following has since been implemented and so I have removed:

- #56 - _"Option to start the arrow at different points other than the first choice"_.
- #87 - _"Option to use arrow keys and shortcuts to move the arrow at the same time"_.
- ee69b658292d3fe1ef1a4584bcca50c7e6bbb04f - Navigation by j and k keys.

This PR now contains the following:
- Introduces an option `use_jk_keys` to enable/disable navigating a list using the `j` and `k` keys.
- Introduces an option `show_selected` to hide/show the selected answer.
- Allow a `Choice` to have no shortcut.
- Improve argument validation.

**Pull request merged**
