### PR TITLE
Fixed #45 (colour of answer for some prompts)

### LINKED ISSUE #45: Color of answer for text prompt doesn't change
I've just switched over from PyInquirer to questionary and it was a seamless transition.  Kudos to you for creating questionary.  One thing I noticed under PyInquirer and a text prompt is that when I get the answer, the answer is high lighted in a different color.  Under questionary, that color doesn't change.  Am I missing something?  I would think that the answer should be able to be styled as the other prompts but I can't get it working no matter what I do.

Thanks.

### PR DESCRIPTION
**Pull request by kiancross**
Fixed #45.

### CODE REVIEW

**Comment by kiancross** [comment]
Had to add some extra commits to fix `black` code style check (they've updated the tool, so previously passing code was failing.

@tmbo Could you review?

**Comment by tmbo** [comment]
> Also no idea why Travis CI - Pull Request Queued — Build Created is stuck on queued?
seems like travis missed to report the result of the build back to github...the build passed ✅

**Review by tmbo — APPROVED** [review]
looks great 🚀

**Comment by tmbo** [comment]
thanks a lot for updating black as well :) can you please update the black version in `requirements-dev.txt` to make sure it stays consistent?

**Comment by kiancross** [comment]
> thanks a lot for updating black as well :) can you please update the black version in `requirements-dev.txt` to make sure it stays consistent?

It looks the version was already set, but the travis file was installing `black` directly and not using the `dev_requirements.txt` file. Fixed now.

**Review by tmbo — APPROVED** [review]
awesome stuff 🚀

**Pull request merged**
